replicaCount: 1
image:
  repository: 339713139704.dkr.ecr.eu-central-1.amazonaws.com/cognipeer-cgate
  pullPolicy: Always
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "cgate"

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:339713139704:certificate/fd8d2d5a-c27c-40ef-ba77-6f06f895c985
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /login
  hosts:
    - host: app.dev.cgate.cognipeer.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
- configMap:
    defaultMode: 420
    name: mongo-ca-bundle
  name: mongo-ca-volume

volumeMounts:
- mountPath: /app/global-bundle.pem
  name: mongo-ca-volume
  subPath: global-bundle.pem

nodeSelector: {}
tolerations: []
affinity: {}
secrets:
  jwt_expires_in: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/JWT_EXPIRES_IN 
  jwt_secret: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/JWT_SECRET
  main_db_name: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/MAIN_DB_NAME
  mongodb_uri: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/MONGODB_URI
  smtp_from: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_FROM
  smtp_host: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_HOST
  smtp_port: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_PORT
  smtp_secure: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_SECURE
  smtp_user: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_USER
  smtp_pass: ref+awssecrets://cgate-application-credentials-dev?region=eu-central-1#/SMTP_PASS