# replicaCount: 3
# image:
#   repository: 339713139704.dkr.ecr.eu-central-1.amazonaws.com/cognipeer-cgate
#   pullPolicy: Always
#   tag: "production"

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# serviceAccount:
#   create: true
#   automount: false
#   annotations: {}
#   name: "cgate"

# podLabels: {}

# podSecurityContext: {}
#   # fsGroup: 2000

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: false
#   runAsUser: 1000
#   runAsGroup: 1000
#   fsGroup: 1000

# service:
#   type: ClusterIP
#   port: 3000

# ingress:
#   enabled: true
#   className: "production"
#   hosts:
#     - host: console.cognipeer.com
#       paths:
#         - path: /
#           pathType: Prefix
#   tls:
#   - hosts:
#     - console.cognipeer.com
#     secretName: cgate-production-tls

# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi

# livenessProbe:
#   tcpSocket:
#     port: 3000
#   initialDelaySeconds: 5
#   periodSeconds: 5

# readinessProbe:
#   tcpSocket:
#     port: 3000
#   initialDelaySeconds: 5
#   periodSeconds: 5

# autoscaling:
#   enabled: false
#   minReplicas: 3
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80

# volumes:
# - configMap:
#     defaultMode: 420
#     name: mongo-ca-bundle
#   name: mongo-ca-volume

# volumeMounts:
# - mountPath: /app/global-bundle.pem
#   name: mongo-ca-volume
#   subPath: global-bundle.pem

# nodeSelector: {}
# tolerations: []
# affinity: {}
