mongodb+srv://master:sc86D1WrOeOEP2CN@cgate-dev.cluster-c7i400koi02w.eu-central-1.docdb.amazonaws.com:27017/
mongodb+srv://master:sc86D1WrOeOEP2CN@cgate-production.cluster-c7i400koi02w.eu-central-1.docdb.amazonaws.com:27017/
