/**
 * Code export — turns an agent's config into a runnable `@cognipeer/agent-sdk`
 * project.
 *
 * Two rules shape everything here.
 *
 * **Inference goes back through the console.** The generated model is an
 * OpenAI-compatible client pointed at `<console>/api/client/v1`, not at the
 * provider. That is the whole governance story: an exported agent still spends
 * against the tenant's quota, still passes the gateway's guardrails, and still
 * shows up in tracing and Cost & Optimization. Pointing it at the raw provider
 * would produce a working agent that is invisible to every control the console
 * exists to provide.
 *
 * **Tools and MCP servers are not re-implemented.** They are reached through
 * `@cognipeer/console-sdk` against the same console. An exported project
 * therefore has no provider credentials in it at all — only a console API key —
 * and a tool whose upstream URL changes keeps working without regenerating.
 *
 * What this is NOT: a round-trip. Generated code is a starting point a team
 * edits; nothing re-imports it. `agentManifest.ts` is the round-trippable form.
 */

import type { IAgent, IAgentConfig, IAgentToolBinding } from '@/lib/database';
import { resolveAgentRuntimeOptions } from './agentRuntimeConfig';

/** What the generated project is shaped to run as. */
export type AgentCodegenTarget =
    /** `npm start "question"` — one shot, prints the answer. */
    | 'cli'
    /** Fastify HTTP service: POST /chat, GET /health, A2A agent card. */
    | 'server'
    /** Long-running queue consumer skeleton (BullMQ-shaped, broker left to the team). */
    | 'worker'
    /** AWS Lambda handler. */
    | 'lambda';

export interface AgentCodegenOptions {
    target: AgentCodegenTarget;
    /** npm package name. Defaults to the agent key. */
    packageName?: string;
    /** Baked into `.env.example` as the default console URL. */
    consoleBaseUrl?: string;
    /** Emit a Dockerfile + .dockerignore. Default: true for `server`/`worker`. */
    includeDockerfile?: boolean;
    /** Emit a `Makefile`-free minimal project (no README). Default: false. */
    omitReadme?: boolean;
}

export interface GeneratedFile {
    path: string;
    contents: string;
    /** Rendered in the download dialog's file tree. */
    description?: string;
}

export interface AgentCodegenResult {
    /** Slugged root folder name inside the archive. */
    rootDir: string;
    files: GeneratedFile[];
    /** Non-fatal things the operator should know before running the project. */
    warnings: string[];
}

const SDK_VERSIONS = {
    agentSdk: '^0.10.1',
    consoleSdk: '^1.7.1',
    langchainOpenAI: '^1.4.4',
    zod: '^3.25.0',
    dotenv: '^16.4.5',
    fastify: '^5.2.0',
    typescript: '^5.7.0',
    tsx: '^4.19.0',
    typesNode: '^22.10.0',
} as const;

// ── Helpers ──────────────────────────────────────────────────────────────

function slug(input: string): string {
    return (
        input
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '') || 'agent'
    );
}

/** `JSON.stringify` with the indentation the generated files use. */
function literal(value: unknown, indent = 2): string {
    return JSON.stringify(value, null, indent) ?? 'undefined';
}

function quote(value: string): string {
    return JSON.stringify(value);
}

function banner(agentName: string): string {
    return [
        '// Generated by Cognipeer Console — Agent code export.',
        `// Source agent: ${agentName}`,
        '//',
        '// Edit freely: nothing re-imports this project. To keep the console copy',
        '// in sync, export/import the YAML manifest instead.',
    ].join('\n');
}

// ── File writers ─────────────────────────────────────────────────────────

function writePackageJson(
    name: string,
    options: AgentCodegenOptions,
    needsConsoleSdk: boolean,
): GeneratedFile {
    const deps: Record<string, string> = {
        '@cognipeer/agent-sdk': SDK_VERSIONS.agentSdk,
        '@langchain/openai': SDK_VERSIONS.langchainOpenAI,
        dotenv: SDK_VERSIONS.dotenv,
        zod: SDK_VERSIONS.zod,
    };
    if (needsConsoleSdk) deps['@cognipeer/console-sdk'] = SDK_VERSIONS.consoleSdk;
    if (options.target === 'server') deps.fastify = SDK_VERSIONS.fastify;

    const entry = { cli: 'src/index.ts', server: 'src/server.ts', worker: 'src/worker.ts', lambda: 'src/lambda.ts' }[
        options.target
    ];

    const scripts: Record<string, string> = {
        dev: `tsx watch ${entry}`,
        build: 'tsc -p tsconfig.json',
        start: options.target === 'lambda' ? 'echo "deploy the built handler to Lambda"' : `node dist/${entry.replace('src/', '').replace('.ts', '.js')}`,
        typecheck: 'tsc --noEmit -p tsconfig.json',
    };

    return {
        path: 'package.json',
        description: 'Dependencies and scripts',
        contents: `${literal({
            name,
            version: '0.1.0',
            private: true,
            type: 'module',
            main: `dist/${entry.replace('src/', '').replace('.ts', '.js')}`,
            scripts,
            dependencies: Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b))),
            devDependencies: {
                '@types/node': SDK_VERSIONS.typesNode,
                tsx: SDK_VERSIONS.tsx,
                typescript: SDK_VERSIONS.typescript,
            },
            engines: { node: '>=20' },
        })}\n`,
    };
}

function writeTsconfig(): GeneratedFile {
    return {
        path: 'tsconfig.json',
        description: 'TypeScript configuration',
        contents: `${literal({
            compilerOptions: {
                target: 'ES2022',
                module: 'ESNext',
                moduleResolution: 'bundler',
                lib: ['ES2022'],
                outDir: 'dist',
                rootDir: 'src',
                strict: true,
                esModuleInterop: true,
                skipLibCheck: true,
                resolveJsonModule: true,
                declaration: false,
                sourceMap: true,
            },
            include: ['src/**/*.ts'],
        })}\n`,
    };
}

function writeEnvExample(options: AgentCodegenOptions, target: AgentCodegenTarget): GeneratedFile {
    const lines = [
        '# Console gateway — the exported agent calls the model and its tools through',
        '# the console, so this is the only credential the project needs.',
        `CONSOLE_BASE_URL=${options.consoleBaseUrl ?? 'https://console.example.com'}`,
        'CONSOLE_API_KEY=',
        '',
        '# Optional: project scope for the API key, when it is a tenant-wide key.',
        '# CONSOLE_PROJECT_ID=',
    ];
    if (target === 'server') lines.push('', 'PORT=3000', 'HOST=0.0.0.0');
    if (target === 'worker') lines.push('', '# Your queue connection string.', '# QUEUE_URL=');
    return { path: '.env.example', description: 'Environment template', contents: `${lines.join('\n')}\n` };
}

function writeGitignore(): GeneratedFile {
    return {
        path: '.gitignore',
        contents: ['node_modules/', 'dist/', '.env', '.env.local', '*.log', '.DS_Store', ''].join('\n'),
    };
}

function writeModel(config: IAgentConfig, agentName: string): GeneratedFile {
    const modelSettings: Record<string, unknown> = {};
    if (config.temperature !== undefined) modelSettings.temperature = config.temperature;
    if (config.topP !== undefined) modelSettings.topP = config.topP;
    if (config.maxTokens !== undefined) modelSettings.maxTokens = config.maxTokens;

    return {
        path: 'src/model.ts',
        description: 'Model, routed through the console gateway',
        contents: `${banner(agentName)}

import { ChatOpenAI } from '@langchain/openai';
import { fromLangchainModel } from '@cognipeer/agent-sdk';

import { env } from './env.js';

/**
 * The model talks to the console's OpenAI-compatible gateway, not to the
 * provider. Keep it that way: it is what makes this agent's spend, guardrails
 * and traces show up in the console alongside the agent it was exported from.
 *
 * \`${config.modelKey ?? '<unset>'}\` is a console model KEY, not a provider
 * model id — the gateway resolves it to whichever deployment the project is
 * currently pointed at.
 */
export function createModel() {
  const lcModel = new ChatOpenAI({
    model: ${quote(config.modelKey ?? '')},
    apiKey: env.CONSOLE_API_KEY,
    configuration: { baseURL: \`\${env.CONSOLE_BASE_URL}/api/client/v1\` },
${Object.entries(modelSettings)
    .map(([key, value]) => `    ${key}: ${literal(value)},`)
    .join('\n')}
  });

  return fromLangchainModel(lcModel);
}
`,
    };
}

function writeEnv(): GeneratedFile {
    return {
        path: 'src/env.ts',
        description: 'Environment loading with an explicit failure',
        contents: `import 'dotenv/config';

function required(name: string): string {
  const value = process.env[name];
  // Failing at import time beats failing on the first model call: a missing key
  // otherwise surfaces as an opaque 401 in the middle of a conversation.
  if (!value) throw new Error(\`Missing required environment variable: \${name}\`);
  return value;
}

export const env = {
  CONSOLE_BASE_URL: required('CONSOLE_BASE_URL').replace(/\\/$/, ''),
  CONSOLE_API_KEY: required('CONSOLE_API_KEY'),
  CONSOLE_PROJECT_ID: process.env.CONSOLE_PROJECT_ID,
  PORT: Number(process.env.PORT ?? 3000),
  HOST: process.env.HOST ?? '0.0.0.0',
};
`,
    };
}

function writeConsoleClient(): GeneratedFile {
    return {
        path: 'src/console.ts',
        description: 'Shared console-sdk client',
        contents: `import { ConsoleClient } from '@cognipeer/console-sdk';

import { env } from './env.js';

/** One client for the process — every tool below shares its connection pool. */
export const console_ = new ConsoleClient({
  baseUrl: env.CONSOLE_BASE_URL,
  apiKey: env.CONSOLE_API_KEY,
});
`,
    };
}

function writeTools(bindings: IAgentToolBinding[], agentName: string): GeneratedFile {
    const toolBindings = bindings.filter((b) => b.source === 'tool');
    const mcpBindings = bindings.filter((b) => b.source === 'mcp');
    const systemBindings = bindings.filter((b) => b.source === 'system');

    const body: string[] = [
        banner(agentName),
        '',
        "import { createTool } from '@cognipeer/agent-sdk';",
        "import { z } from 'zod';",
        '',
        "import { console_ } from './console.js';",
        '',
        '/**',
        ' * Tool surface, resolved from the console at startup.',
        ' *',
        ' * Schemas are fetched rather than inlined on purpose: an OpenAPI action or',
        ' * an MCP server that gains a parameter stays correct here without a',
        ' * regenerate. The trade-off is one round trip per source at boot.',
        ' */',
        'export async function buildTools() {',
        '  const tools = [];',
        '',
    ];

    for (const binding of toolBindings) {
        const allow = binding.toolNames?.length ? binding.toolNames : null;
        body.push(
            `  // Console tool source: ${binding.sourceKey}`,
            '  {',
            `    const definition = await console_.tools.get(${quote(binding.sourceKey)});`,
            `    const allowed = ${allow ? literal(allow, 0) : 'null'};`,
            '    for (const action of definition.actions ?? []) {',
            '      if (allowed && !allowed.includes(action.name)) continue;',
            '      tools.push(createTool({',
            '        name: action.name,',
            '        description: action.description || action.name,',
            '        // The console validates the real schema on execute; a permissive',
            '        // passthrough here avoids a second, drifting copy of it.',
            '        schema: z.object({}).passthrough(),',
            '        execute: async (args: Record<string, unknown>) =>',
            `          console_.tools.execute(${quote(binding.sourceKey)}, action.key, args),`,
            '      }));',
            '    }',
            '  }',
            '',
        );
    }

    for (const binding of mcpBindings) {
        const allow = binding.toolNames?.length ? binding.toolNames : null;
        body.push(
            `  // MCP server: ${binding.sourceKey}`,
            '  {',
            `    const server = console_.mcp.server(${quote(binding.sourceKey)});`,
            '    const descriptors = await server.listTools();',
            `    const allowed = ${allow ? literal(allow, 0) : 'null'};`,
            '    for (const descriptor of descriptors) {',
            '      if (allowed && !allowed.includes(descriptor.name)) continue;',
            '      tools.push(createTool({',
            '        name: descriptor.name,',
            '        description: descriptor.description || descriptor.name,',
            '        schema: z.object({}).passthrough(),',
            '        execute: async (args: Record<string, unknown>) =>',
            '          server.callTool(descriptor.name, args),',
            '      }));',
            '    }',
            '  }',
            '',
        );
    }

    if (systemBindings.length > 0) {
        body.push(
            '  // Built-in console tools are part of the console runtime and have no',
            '  // standalone equivalent. Re-bind them by calling the console agent, or',
            '  // replace them with your own implementation:',
            ...systemBindings.map((b) => `  //   - ${b.sourceKey} (${b.toolNames.join(', ') || 'all actions'})`),
            '',
        );
    }

    body.push('  return tools;', '}', '');
    return { path: 'src/tools.ts', description: 'Tools and MCP servers via console-sdk', contents: body.join('\n') };
}

function writeKnowledge(knowledgeEngineKey: string, agentName: string): GeneratedFile {
    return {
        path: 'src/knowledge.ts',
        description: 'Retrieval tool backed by the console knowledge engine',
        contents: `${banner(agentName)}

import { createTool } from '@cognipeer/agent-sdk';
import { z } from 'zod';

import { console_ } from './console.js';

const MODULE_KEY = ${quote(knowledgeEngineKey)};

/**
 * Mirrors the console agent's \`knowledge_search\`, including the instruction
 * text — the retrieval-first behaviour comes from that description as much as
 * from the system prompt.
 */
export function createKnowledgeTool() {
  return createTool({
    name: 'knowledge_search',
    description:
      'PRIMARY retrieval tool. For factual, product, policy, API, docs, or troubleshooting ' +
      'questions, call this tool BEFORE drafting the final answer. Use the user question ' +
      '(or a focused rewrite) as query.',
    schema: z.object({
      query: z.string().describe('The search query'),
      topK: z.number().int().min(1).max(20).optional(),
    }),
    execute: async ({ query, topK }: { query: string; topK?: number }) => {
      const result = await console_.rag.query(MODULE_KEY, { query, topK: topK ?? 5 });
      return result;
    },
  });
}
`,
    };
}

function writeSubagents(config: IAgentConfig, agentName: string): GeneratedFile {
    const entries = (config.subagents ?? []).filter((s) => s.enabled !== false);
    const lines: string[] = [
        banner(agentName),
        '',
        "import type { SubagentDef } from '@cognipeer/agent-sdk';",
        '',
        '/**',
        ' * Sub-agents the orchestrator can delegate to.',
        ' *',
        " * A `ref` sub-agent pointed at another console agent is exported as its own",
        ' * definition here — the export is a snapshot, so changing that agent in the',
        ' * console no longer changes this project. That is the intended trade: an',
        ' * exported project must be reproducible from its own source.',
        ' */',
        'export function buildSubagents(parentTools: unknown[]): SubagentDef[] {',
        '  return [',
    ];

    for (const entry of entries) {
        const childToolNames = (entry.toolBindings ?? []).flatMap((b) => b.toolNames ?? []);
        lines.push(
            '    {',
            `      name: ${quote(entry.name)},`,
            ...(entry.title ? [`      title: ${quote(entry.title)},`] : []),
            `      header: ${quote(entry.header || entry.title || entry.name)},`,
            ...(entry.systemPrompt ? [`      systemPrompt: ${quote(entry.systemPrompt)},`] : []),
            ...(childToolNames.length > 0
                ? [
                    `      // Resolved by name against the parent's live tool set at spawn time.`,
                    `      tools: ${literal(childToolNames, 0)},`,
                ]
                : []),
            ...(entry.limits ? [`      limits: ${literal(entry.limits, 6)},`] : []),
            ...(entry.childContextPolicy
                ? [`      childContextPolicy: ${quote(entry.childContextPolicy)},`]
                : []),
            '    },',
        );
    }

    lines.push('  ];', '}', '');
    return { path: 'src/subagents.ts', description: 'Delegable sub-agents', contents: lines.join('\n') };
}

function writeAgent(
    agent: Pick<IAgent, 'key' | 'name'>,
    config: IAgentConfig,
    flags: { hasTools: boolean; hasKnowledge: boolean; hasSubagents: boolean; hasStructuredOutput: boolean },
): GeneratedFile {
    const runtime = resolveAgentRuntimeOptions(config);
    const imports = [
        "import { createSmartAgent } from '@cognipeer/agent-sdk';",
        ...(flags.hasStructuredOutput ? ["import { z } from 'zod';"] : []),
        '',
        "import { createModel } from './model.js';",
        ...(flags.hasTools ? ["import { buildTools } from './tools.js';"] : []),
        ...(flags.hasKnowledge ? ["import { createKnowledgeTool } from './knowledge.js';"] : []),
        ...(flags.hasSubagents ? ["import { buildSubagents } from './subagents.js';"] : []),
    ];

    // `tools` is declared whenever anything downstream reads it — sub-agents
    // resolve their tool names against the parent's live set, so an agent with
    // sub-agents but no tools still needs the (empty) binding.
    const needsToolsBinding = flags.hasKnowledge || flags.hasTools || flags.hasSubagents;
    const toolLines: string[] = [];
    if (needsToolsBinding) {
        toolLines.push('  const tools = [');
        if (flags.hasKnowledge) toolLines.push('    createKnowledgeTool(),');
        if (flags.hasTools) toolLines.push('    ...(await buildTools()),');
        toolLines.push('  ];', '');
    }

    const structured = flags.hasStructuredOutput
        ? [
            '  // Structured output contract. Regenerate after editing the schema in the',
            '  // console, or edit it here — this file is yours now.',
            `  const outputSchema = ${zodLiteralFromJsonSchema(config.structuredOutput?.schema, config.structuredOutput?.strict === true, 2)};`,
            '',
        ]
        : [];

    const options: string[] = [
        `    name: ${quote(agent.name)},`,
        ...(config.systemPrompt ? [`    systemPrompt: SYSTEM_PROMPT,`] : []),
        '    model: createModel(),',
        ...(flags.hasKnowledge || flags.hasTools ? ['    tools,'] : []),
        ...(flags.hasSubagents ? ['    subagents: buildSubagents(tools),'] : []),
        ...(flags.hasStructuredOutput ? ['    outputSchema,'] : []),
        `    runtimeProfile: ${quote(runtime.runtimeProfile ?? 'balanced')},`,
        `    planning: ${literal(runtime.planning, 4)},`,
        `    limits: ${literal(runtime.limits, 4)},`,
        `    summarization: ${literal(runtime.summarization, 4)},`,
        `    context: ${literal(runtime.context, 4)},`,
        `    toolResponses: ${literal(runtime.toolResponses, 4)},`,
        ...(runtime.contextPilot ? [`    contextPilot: ${literal(runtime.contextPilot, 4)},`] : []),
        ...(runtime.reasoning ? [`    reasoning: ${literal(runtime.reasoning, 4)},`] : []),
        ...(runtime.subagentPolicy ? [`    subagentPolicy: ${literal(runtime.subagentPolicy, 4)},`] : []),
    ];

    return {
        path: 'src/agent.ts',
        description: 'The agent definition',
        contents: `${banner(agent.name)}

${imports.join('\n')}

${config.systemPrompt ? `const SYSTEM_PROMPT = ${quote(config.systemPrompt)};\n` : ''}
export async function createAgent() {
${toolLines.join('\n')}${structured.join('\n')}  return createSmartAgent({
${options.join('\n')}
  });
}
`,
    };
}

/** Emits a zod expression for a JSON Schema. Falls back to `z.any()`. */
function zodLiteralFromJsonSchema(schema: unknown, strict: boolean, indent: number): string {
    const pad = ' '.repeat(indent);
    if (!schema || typeof schema !== 'object') return 'z.any()';
    const node = schema as Record<string, any>;

    if (Array.isArray(node.enum) && node.enum.every((v: unknown) => typeof v === 'string')) {
        return `z.enum(${literal(node.enum, 0)})`;
    }

    const type = Array.isArray(node.type) ? node.type.find((t: string) => t !== 'null') : node.type;
    switch (type) {
        case 'string':
            return describe('z.string()', node);
        case 'integer':
            return describe('z.number().int()', node);
        case 'number':
            return describe('z.number()', node);
        case 'boolean':
            return describe('z.boolean()', node);
        case 'array':
            return describe(`z.array(${zodLiteralFromJsonSchema(node.items, strict, indent)})`, node);
        case 'object': {
            const required: string[] = Array.isArray(node.required) ? node.required : [];
            const properties: Record<string, unknown> = node.properties ?? {};
            const entries = Object.entries(properties).map(([key, value]) => {
                const child = zodLiteralFromJsonSchema(value, strict, indent + 2);
                const optional = strict || required.includes(key) ? '' : '.optional()';
                return `${pad}  ${JSON.stringify(key)}: ${child}${optional},`;
            });
            if (entries.length === 0) return 'z.object({})';
            const suffix = strict || node.additionalProperties === false ? '.strict()' : '';
            return describe(`z.object({\n${entries.join('\n')}\n${pad}})${suffix}`, node);
        }
        default:
            return 'z.any()';
    }

    function describe(expr: string, source: Record<string, any>): string {
        return typeof source.description === 'string' && source.description
            ? `${expr}.describe(${quote(source.description)})`
            : expr;
    }
}

function writeEntrypoint(target: AgentCodegenTarget, agent: Pick<IAgent, 'key' | 'name' | 'description'>): GeneratedFile {
    switch (target) {
        case 'server':
            return {
                path: 'src/server.ts',
                description: 'Fastify service with /chat, /health and an A2A agent card',
                contents: `import Fastify from 'fastify';

import { createAgent } from './agent.js';
import { env } from './env.js';

const app = Fastify({ logger: true });

// Built once at boot, not per request: tool discovery costs a round trip per
// source, and the agent object is stateless across invokes.
const agent = await createAgent();

app.get('/health', async () => ({ status: 'ok' }));

/**
 * A2A discovery document. The console can register this URL as a connected
 * agent, which is how an exported project gets back into the platform's
 * routing without being re-imported.
 */
app.get('/.well-known/agent.json', async () => ({
  name: ${quote(agent.name)},
  description: ${quote(agent.description ?? '')},
  url: \`http://\${env.HOST}:\${env.PORT}\`,
  version: '0.1.0',
  capabilities: { streaming: false },
  defaultInputModes: ['text'],
  defaultOutputModes: ['text'],
  skills: [],
}));

app.post<{ Body: { message?: string; messages?: Array<{ role: string; content: string }> } }>(
  '/chat',
  async (request, reply) => {
    const { message, messages } = request.body ?? {};
    const input = messages ?? (message ? [{ role: 'user', content: message }] : null);
    if (!input) return reply.status(400).send({ error: 'message or messages is required' });

    const result = await agent.invoke({ messages: input });
    return { content: result.content, output: result.output, usage: result.usage };
  },
);

await app.listen({ port: env.PORT, host: env.HOST });
`,
            };
        case 'worker':
            return {
                path: 'src/worker.ts',
                description: 'Queue consumer skeleton',
                contents: `import { createAgent } from './agent.js';

/**
 * Queue consumer skeleton. The broker is deliberately left out — swap
 * \`nextJob\`/\`ack\` for BullMQ, SQS or whatever the team already runs.
 *
 * The two things worth keeping: the agent is created ONCE outside the loop, and
 * every job carries an idempotency key so a redelivery does not produce a second
 * answer (and a second bill).
 */
const agent = await createAgent();

type Job = { id: string; idempotencyKey: string; question: string };

async function nextJob(): Promise<Job | null> {
  throw new Error('Wire this to your queue');
}

async function handle(job: Job) {
  const result = await agent.invoke({ messages: [{ role: 'user', content: job.question }] });
  return { idempotencyKey: job.idempotencyKey, content: result.content };
}

async function main() {
  for (;;) {
    const job = await nextJob();
    if (!job) break;
    await handle(job);
  }
}

await main();
`,
            };
        case 'lambda':
            return {
                path: 'src/lambda.ts',
                description: 'AWS Lambda handler',
                contents: `import { createAgent } from './agent.js';

/**
 * The agent is built at module scope so a warm container reuses it. Tool
 * discovery is the expensive part of \`createAgent()\`; paying it per invocation
 * would dominate a short request.
 */
const agentPromise = createAgent();

export async function handler(event: { body?: string }) {
  const body = event.body ? JSON.parse(event.body) : {};
  const message = body.message;
  if (!message) {
    return { statusCode: 400, body: JSON.stringify({ error: 'message is required' }) };
  }

  const agent = await agentPromise;
  const result = await agent.invoke({ messages: [{ role: 'user', content: message }] });
  return { statusCode: 200, body: JSON.stringify({ content: result.content, usage: result.usage }) };
}
`,
            };
        case 'cli':
        default:
            return {
                path: 'src/index.ts',
                description: 'CLI entrypoint',
                contents: `import { createAgent } from './agent.js';

const question = process.argv.slice(2).join(' ');
if (!question) {
  console.error('Usage: npm start -- "your question"');
  process.exit(1);
}

const agent = await createAgent();
const result = await agent.invoke({ messages: [{ role: 'user', content: question }] });

console.log(result.content);
if (result.output) console.log(JSON.stringify(result.output, null, 2));
`,
            };
    }
}

function writeDockerfile(target: AgentCodegenTarget): GeneratedFile[] {
    const entry = target === 'worker' ? 'worker.js' : 'server.js';
    return [
        {
            path: 'Dockerfile',
            description: 'Container image',
            contents: `FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
${target === 'server' ? 'EXPOSE 3000\n' : ''}CMD ["node", "dist/${entry}"]
`,
        },
        {
            path: '.dockerignore',
            contents: ['node_modules', 'dist', '.env', '.git', '*.log', ''].join('\n'),
        },
    ];
}

function writeReadme(
    agent: Pick<IAgent, 'key' | 'name' | 'description'>,
    options: AgentCodegenOptions,
    warnings: string[],
): GeneratedFile {
    const runCommand = {
        cli: 'npm start -- "your question"',
        server: 'npm run dev   # POST http://localhost:3000/chat',
        worker: 'npm run dev',
        lambda: 'npm run build  # then deploy dist/lambda.js',
    }[options.target];

    return {
        path: 'README.md',
        description: 'How to run it',
        contents: `# ${agent.name}

${agent.description ? `${agent.description}\n` : ''}
Exported from Cognipeer Console (agent \`${agent.key}\`) as a **${options.target}** project
built on [\`@cognipeer/agent-sdk\`](https://www.npmjs.com/package/@cognipeer/agent-sdk).

## Run it

\`\`\`bash
cp .env.example .env    # fill in CONSOLE_API_KEY
npm install
${runCommand}
\`\`\`

## How it talks to the console

The project holds **one** credential: a console API key.

- **Model calls** go to \`\${CONSOLE_BASE_URL}/api/client/v1\` (OpenAI-compatible).
  Spend, quota, guardrails and tracing therefore still apply — the exported agent
  is not invisible to the platform.
- **Tools and MCP servers** are resolved through \`@cognipeer/console-sdk\` at
  startup, so their credentials and upstream URLs stay in the console.

There are no provider keys in this repository, and there should never be.

## What does *not* come across

| Console feature | Status in this project |
|---|---|
| Guardrails | Enforced by the gateway, not by this code |
| Version history | Frozen — this is one snapshot |
| Conversation storage | Not included; the entrypoints are stateless |
| Built-in tools (browser_use, …) | Console-runtime only; see \`src/tools.ts\` |
${warnings.length > 0 ? `\n## Export warnings\n\n${warnings.map((w) => `- ${w}`).join('\n')}\n` : ''}
## Keeping it in sync

Nothing re-imports this code. To move the agent between environments, use the
YAML manifest export instead — it round-trips.
`,
    };
}

// ── Entry point ──────────────────────────────────────────────────────────

export function generateAgentProject(
    agent: Pick<IAgent, 'key' | 'name' | 'description'>,
    config: IAgentConfig,
    options: AgentCodegenOptions,
): AgentCodegenResult {
    const warnings: string[] = [];
    const rootDir = slug(options.packageName || agent.key);

    if (config.kind === 'external') {
        warnings.push(
            'This is a connected (external) agent: it has no local model or tools, so the generated project is a thin HTTP client shell. Point it at the same endpoint the console uses.',
        );
    }

    const bindings = config.toolBindings ?? [];
    const hasTools = bindings.some((b) => b.source === 'tool' || b.source === 'mcp');
    const hasSystemTools = bindings.some((b) => b.source === 'system');
    const hasKnowledge = Boolean(config.knowledgeEngineKey);
    const hasSubagents = (config.subagents ?? []).some((s) => s.enabled !== false);
    const hasStructuredOutput = Boolean(config.structuredOutput?.enabled && config.structuredOutput.schema);
    const needsConsoleSdk = hasTools || hasKnowledge;

    if (hasSystemTools) {
        warnings.push(
            'Built-in console tools (e.g. browser_use) run inside the console runtime and have no standalone equivalent; they are listed as comments in src/tools.ts.',
        );
    }
    if ((config.guardrails?.length ?? 0) > 0) {
        warnings.push(
            'Guardrails stay on the console gateway. They still apply to model calls, but this project does not evaluate them locally — a tool result is not guardrailed here.',
        );
    }
    if (config.promptKey) {
        warnings.push(
            `The system prompt comes from prompt "${config.promptKey}"; the generated project inlines the text that was resolved at export time and will not follow later prompt edits.`,
        );
    }
    if ((config.subagents ?? []).some((s) => s.kind === 'ref')) {
        warnings.push(
            'Referenced sub-agents were flattened into src/subagents.ts at export time. Editing the referenced agent in the console no longer affects this project.',
        );
    }
    if (config.memory?.enabled) {
        warnings.push(
            'Memory is not included in the export: it is backed by this console\'s own Memory module, which the generated project has no credentials or client for. The agent runs without recall/write here.',
        );
    }
    if ((config.skills?.length ?? 0) > 0) {
        warnings.push(
            'Skills are not included in the export: the skill library lives in this console. Copy the skill text from Settings → Skills into the generated agent\'s systemPrompt if you need it standalone.',
        );
    }

    const files: GeneratedFile[] = [
        writePackageJson(slug(options.packageName || agent.key), options, needsConsoleSdk),
        writeTsconfig(),
        writeEnvExample(options, options.target),
        writeGitignore(),
        writeEnv(),
        writeModel(config, agent.name),
    ];

    if (needsConsoleSdk) files.push(writeConsoleClient());
    if (hasTools || hasSystemTools) files.push(writeTools(bindings, agent.name));
    if (hasKnowledge) files.push(writeKnowledge(config.knowledgeEngineKey!, agent.name));
    if (hasSubagents) files.push(writeSubagents(config, agent.name));

    files.push(
        writeAgent(agent, config, {
            hasTools: hasTools || hasSystemTools,
            hasKnowledge,
            hasSubagents,
            hasStructuredOutput,
        }),
    );
    files.push(writeEntrypoint(options.target, agent));

    const wantsDocker = options.includeDockerfile ?? (options.target === 'server' || options.target === 'worker');
    if (wantsDocker) files.push(...writeDockerfile(options.target));
    if (!options.omitReadme) files.push(writeReadme(agent, options, warnings));

    return { rootDir, files, warnings };
}
