environments:
  dev-aws:
    values:
      - values/dev-aws.yaml
  production-aws:
    values:
      - values/production-aws.yaml
  production-azure:
    values:
      - values/production-azure.yaml
  dev-azure:
    values:
      - values/dev-azure.yaml
---
releases:
  - name: cgate
    namespace: cgate-{{.Environment.Name}}
    createNamespace: true
    chart: ./cgate
    values:
    - values/{{.Environment.Values.cloudEnvironment}}-common.yaml.gotmpl
    - values/{{ .Environment.Name }}.yaml
