environments:
  dev:
    values:
      - values/dev.yaml
  production:
    values:
      - values/production.yaml
---
releases:
  - name: cgate
    namespace: cgate-{{.Environment.Name}}
    createNamespace: true
    chart: ./cgate
    values:
    - values/common.yaml.gotmpl