environments:
  dev:
    values:
      - values/dev.yaml
  production:
    values:
      - values/production.yaml
---
releases:
  - name: cognipeer-console
    namespace: cognipeer-console-{{.Environment.Name}}
    createNamespace: true
    chart: ./cognipeer-console
    values:
    - values/common.yaml.gotmpl