apiVersion: v1
data:
  JWT_EXPIRES_IN: {{.Values.secrets.jwt_expires_in | b64enc }}
  JWT_SECRET: {{.Values.secrets.jwt_secret | b64enc }}
  MAIN_DB_NAME: {{.Values.secrets.main_db_name | b64enc }}
  MONGODB_URI: {{.Values.secrets.mongodb_uri | b64enc }}
  SMTP_FROM: {{.Values.secrets.smtp_from | b64enc }}
  SMTP_HOST: {{.Values.secrets.smtp_host | b64enc }}
  SMTP_PASS: {{.Values.secrets.smtp_pass | b64enc }}
  SMTP_PORT: {{.Values.secrets.smtp_port | b64enc }}
  SMTP_SECURE: {{.Values.secrets.smtp_secure | b64enc }}
  SMTP_USER: {{.Values.secrets.smtp_user | b64enc }}
kind: Secret
metadata:
  name: cgate-application-secrets
type: Opaque