{{- if contains "aws" (.Values.cloudEnvironment | toString) }}
{{- if .Values.secrets -}}
apiVersion: v1
data:
  {{- range $key, $val := .Values.secrets }}
  {{$key | upper}}: {{ $val | b64enc }}
  {{- end }}  
kind: Secret
metadata:
  name: cgate-application-secrets
type: Opaque
{{- end }}
{{- end }}