{{- if contains "aws" (.Values.cloudEnvironment | toString) }}
apiVersion: v1
data:
  tls.crt: "{{.Values.tls_secrets.fullchain_pem}}"
  tls.key: "{{.Values.tls_secrets.privatekey_pem}}"
kind: Secret
metadata:
  name: cgate-{{.Values.environment}}-tls
  namespace: cgate-{{.Values.environment}}
type: kubernetes.io/tls
{{- end }}