name: Cgate Build Artifact

on:
  push:
    branches:
    - main
    - production
    - infra/fix-gh-action

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: cognipeer-cgate
  HELM_VERSION: v3.15.2
  HELMFILE_VERSION: v0.162.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "production" ]]; then
            echo "tag=production" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: self-hosted-runner-cgate
    steps:
      - name: Apply changes
        run: |
          echo "The environment is ${steps.vars.outputs.tag} "
          #helmfile sync -e "${steps.vars.outputs.tag}"
